name: MikeDeets
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7581
title: Direct Selling with Mike Deets
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#924500'
    - '#e5a514'
    - '#808080'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
